# Generated by Django 4.1.7 on 2023-04-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_tag_rename_profile_skill_skill_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("P", "Personal"), ("C", "Commercial")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[("A", "Award"), ("C", "Certificates"), ("T", "Title")],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "achievement_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
