# Generated by Django 4.1.7 on 2023-04-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_award_education_experience_skill_svg_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("commercial", "Commercial")],
                max_length=20,
            ),
        ),
    ]
