# Generated by Django 4.1.7 on 2023-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="svg_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
